variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libv8-dev"

image: bioconductor/bioconductor_docker:devel

devtools-check:
  stage: test
  tags:
    - methylationprojects_docker
  script:
    - R -e 'devtools::check()'