variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libv8-dev"

image: bioconductor/bioconductor_docker:devel

before_script:
  - apt-get update
  - Rscript -e "options(repos = c(CRAN = 'https://cran.r-project.org')); BiocManager::install(ask=FALSE)"
  - Rscript -e "options(repos = c(CRAN = 'https://cran.r-project.org')); devtools::install('.', dependencies=TRUE, build_vignettes=TRUE, repos = BiocManager::repositories())"

build:
  stage: build
  tags: 
    - methylationprojects
  script:
    - echo "Do your build here"
    - pwd && ls -lah
    - cat "FROM bioconductor/bioconductor_docker:devel" > Dockerfile
    - cat "WORKDIR /home/rstudio" >> Dockerfile
    - cat "COPY --chown=rstudio:rstudio . /home/rstudio/" >> Dockerfile
    - cat "RUN Rscript installDependencies.R" >> Dockerfile
    - docker build -t crukmi/mesa_dependencies .

devtools-check:
  stage: test
  tags:
    - methylationprojects_docker
  script:
    - R -e 'devtools::check()'
