variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libv8-dev"

stages:
  - deploy

build:
  stage: deploy
  tags:
    - methylationprojects
  script:
    - echo "Building container for docker"
    - pwd && ls -lah
    - docker build -t mesa_test -f Dockerfile .
    - docker login sc-docker-registry.scicom.picr.man.ac.uk:5000 -u crukmi -p crukmi
    - docker push sc-docker-registry.scicom.picr.man.ac.uk:5000/mesa_test:0.0.1

  rules:
    - changes:  # Run the job if any of these files changes
        - DESCRIPTION
        - Dockerfile_dependencies_only
        - installDependencies.R

devtools-check:
  image: crukmi/mesa_dependencies:latest
  stage: test
  tags:
    - methylationprojects_docker
  script:
    - R -e 'devtools::check()'
    