FROM bioconductor/bioconductor_docker:RELEASE_3_16-R-4.2.3

WORKDIR /home/rstudio

COPY --chown=rstudio:rstudio . /home/rstudio/

RUN apt-get update
RUN apt-get install -y qpdf
RUN Rscript installDependencies.R
